# Generated by Django 2.1.5 on 2019-05-13 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=128, verbose_name='ページURL')),
                ('page_html', models.TextField(verbose_name='html')),
                ('code', models.CharField(max_length=100, verbose_name='コード')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='補足')),
                ('company_name', models.CharField(max_length=100, verbose_name='会社名')),
                ('phone_number', models.CharField(max_length=50, verbose_name='電話番号')),
                ('is_callable', models.BooleanField(default=False, verbose_name='電話可能')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myparent', to='main.Page', verbose_name='親ページ')),
            ],
        ),
    ]
