# Generated by Django 2.1.5 on 2019-05-13 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190513_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='main.Group', verbose_name='グループ'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.Page', verbose_name='親ページ'),
        ),
    ]
