# Generated by Django 2.1.5 on 2019-05-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190513_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='display_order',
            field=models.IntegerField(default=1, verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='page',
            name='display_order',
            field=models.IntegerField(default=1, verbose_name='表示順'),
        ),
    ]
