# Generated by Django 2.1.5 on 2019-05-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190515_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='コード'),
        ),
        migrations.AlterField(
            model_name='page',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='補足'),
        ),
        migrations.AlterField(
            model_name='page',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_html',
            field=models.TextField(blank=True, default='', null=True, verbose_name='html'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_url',
            field=models.URLField(blank=True, default='', max_length=128, null=True, verbose_name='ページURL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='電話番号'),
        ),
    ]
