# Generated by Django 2.1.5 on 2019-05-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190515_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(blank=True, default='', max_length=128, null=True, verbose_name='ページURL')),
                ('page_html', models.TextField(blank=True, default='', null=True, verbose_name='html')),
                ('code', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='コード')),
                ('comment', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='補足')),
                ('company_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='会社名')),
                ('market_cap', models.IntegerField(blank=True, default=0, null=True, verbose_name='時価総額')),
                ('phone_number', models.CharField(blank=True, default='', max_length=50, verbose_name='電話番号')),
                ('is_callable', models.BooleanField(default=False, verbose_name='電話可能')),
                ('display_order', models.IntegerField(default=1, verbose_name='表示順')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='main.Group', verbose_name='グループ')),
            ],
        ),
        migrations.CreateModel(
            name='LinkPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(blank=True, default='', max_length=128, null=True, verbose_name='ページURL')),
                ('page_html', models.TextField(blank=True, default='', null=True, verbose_name='html')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.CompanyHomePage', verbose_name='親ページ')),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='group',
        ),
        migrations.RemoveField(
            model_name='page',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
