# Generated by Django 2.1.5 on 2019-05-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190516_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyhomepage',
            name='memo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='memo',
            field=models.TextField(default=''),
        ),
    ]
