# Generated by Django 2.1.5 on 2019-05-29 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190528_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageGroupOrComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_or_comment', models.CharField(max_length=100)),
                ('comment', models.TextField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='main.Group', verbose_name='グループ')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.CompanyHomePage')),
            ],
        ),
        migrations.RemoveField(
            model_name='pagegroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='pagegroup',
            name='page',
        ),
        migrations.DeleteModel(
            name='PageGroup',
        ),
    ]
