# Generated by Django 2.1.5 on 2019-05-29 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190529_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageGroupOrMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_or_comment', models.CharField(max_length=100)),
                ('memo', models.TextField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='main.Group', verbose_name='グループ')),
            ],
        ),
        migrations.RemoveField(
            model_name='pagegrouporcomment',
            name='group',
        ),
        migrations.RemoveField(
            model_name='pagegrouporcomment',
            name='page',
        ),
        migrations.RemoveField(
            model_name='companyhomepage',
            name='memo',
        ),
        migrations.DeleteModel(
            name='PageGroupOrComment',
        ),
        migrations.AddField(
            model_name='pagegroupormemo',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.CompanyHomePage'),
        ),
    ]
