# Generated by Django 2.1.5 on 2019-05-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190529_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagegroupormemo',
            old_name='page_or_comment',
            new_name='page_or_memo',
        ),
    ]
