# Generated by Django 2.1.5 on 2019-06-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190529_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagegroupormemo',
            name='display_order',
            field=models.IntegerField(default=1, verbose_name='表示順'),
        ),
    ]
