# Generated by Django 2.1.5 on 2019-06-02 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_pagegroupormemo_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=1, verbose_name='表示順')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='main.Group', verbose_name='グループ')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.CompanyHomePage')),
            ],
        ),
        migrations.RemoveField(
            model_name='pagegroupormemo',
            name='group',
        ),
        migrations.RemoveField(
            model_name='pagegroupormemo',
            name='page',
        ),
        migrations.DeleteModel(
            name='PageGroupOrMemo',
        ),
    ]
