# Generated by Django 2.1.5 on 2019-06-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190602_0334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagegroup',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='companyhomepage',
            name='memo',
            field=models.TextField(default='', verbose_name='メモ'),
        ),
    ]
