# Generated by Django 2.1.5 on 2019-06-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190602_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='名前'),
        ),
    ]
