# Generated by Django 2.1.5 on 2019-06-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190602_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhomepage',
            name='market_cap',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='時価総額'),
        ),
    ]
