# Generated by Django 2.1.5 on 2019-06-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190605_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyhomepage',
            name='company_name_kana',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='読み方'),
        ),
    ]
